# Generated by Django 3.2.18 on 2023-03-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.CharField(max_length=255)),
                ('backdrop_path', models.CharField(max_length=255)),
                ('popularity', models.FloatField()),
                ('adult', models.BooleanField()),
                ('imdb_id', models.CharField(max_length=255)),
                ('genre_ids', models.ManyToManyField(to='api.Genre')),
            ],
        ),
    ]
